#!/bin/bash

set -e
set -u

usage="Usage: %s: [SPEC]"

SPEC=""

if test -z "$*"; then
  printf "${USAGE}" $0
  exit 1
fi
SPEC="$1"

sudo yum -q -y install centos-packager epel-release
rpmdev-setuptree

spectool -g -R ${SPEC}
# cp *patch ~/rpmbuild/SOURCES
sudo yum-builddep -q -y ${SPEC}

rpmbuild -ba ${SPEC}

rpmlint ~/rpmbuild/RPMS/*/* || true

mkdir ~/source/packages
cp -r ~/rpmbuild/RPMS ~/rpmbuild/SRPMS ~/source/packages
