#!/usr/bin/env python

from __future__ import print_function
import argparse
import os
import subprocess
import sys

def main():
    parser = argparse.ArgumentParser()
    arguments = parser.parse_args()
    
    local_root = os.path.abspath(os.path.dirname(__file__))

    for repository in get_repositories(local_root):
        sign_packages(repository)
        update_repo(repository)
        sign_repo(repository)            

def get_repositories(local_root):
    distributions = ["centos"]
    
    repositories = []
    for distribution in distributions:
        for release in os.listdir(os.path.join(local_root, distribution)):
            repositories.append(os.path.join(local_root, distribution, release))
    return repositories

def sign_packages(repository):
    unsigned_packages = []
    for dirpath, dirnames, filenames in os.walk(repository):
        for filename in filenames:
            if not filename.endswith(".rpm"):
                continue
            
            package = os.path.join(dirpath, filename)
            
            is_signed = "pgp" in subprocess.check_output(["rpm", "--checksig", package])
            if not is_signed:
                unsigned_packages.append(package)
    if unsigned_packages:
        subprocess.check_call(["rpm", "--addsign"]+unsigned_packages)

def update_repo(repository):
    subprocess.check_call(["createrepo", repository])

def sign_repo(repository):
    subprocess.check_call([
        "gpg", "--detach-sign", "--armor", "--yes",
        "--default-key", "3EBD1CD4",
        os.path.join(repository, "repodata", "repomd.xml")])

if __name__ == "__main__":
    sys.exit(main())
