#!/bin/sh

set -e
set -u

# Parse the command-line arguments
parse_args ( ) {
  JOBS=1
  PATCH=""
  UNOFFICIAL_REPO=""
  
  usage="Usage: %s: [-j JOBS] [-u] PROJECT CONTACT\n"

  while getopts "c:j:p:u" OPT; do
    case ${OPT} in
      j) JOBS=${OPTARG} ;;
      p) PATCH=${OPTARG} ;;
      u) UNOFFICIAL_REPO="yes" ;;
      ?) 
        printf "${USAGE}" $0
        exit 2;;
    esac
  done

  shift $(($OPTIND - 1))
  
  if test -z "$*"; then
    printf "${USAGE}" $0
    exit 1
  fi
  PROJECT="$1"

  shift

  if test -z "$*"; then
    printf "${USAGE}" $0
    exit 1
  fi
  DEBEMAIL="$1"
  export DEBEMAIL
}

prepare ( ) {
  APT_GET="apt-get -y --no-install-recommends"
  PATCHES=https://raw.githubusercontent.com/lamyj/packages/master/apt/patches
  BINTRAY=http://dl.bintray.com/lamyj/generic

  sudo rm -f /etc/apt/apt.conf.d/docker-clean
  sudo -E ${APT_GET} update
  sudo -E ${APT_GET} install gnupg wget lsb-release

  DISTRIB=$(lsb_release -cs)

  PACKAGES="apt-utils devscripts dpkg-dev equivs libwww-perl"
  # Needed for uscan on https
  if [ "${DISTRIB}" = "wheezy" -o "${DISTRIB}" = "precise" -o "${DISTRIB}" = "saucy" ]; then
    PACKAGES="${PACKAGES} libcrypt-ssleay-perl"
  fi

  if test -n "${UNOFFICIAL_REPO}"; then
    wget -O - ${BINTRAY}/gpg.key | sudo apt-key add -
    echo "deb ${BINTRAY}/apt ${DISTRIB} main" | sudo tee -a /etc/apt/sources.list
    sudo -E ${APT_GET} update
  fi
  sudo -E ${APT_GET} install ${PACKAGES}
  
  # WARNING: bionic requires build and its parent to be under the same mount
  cp -a source build
  cd build
  
  # Patch if needed
  if test -n "${PATCH}"; then
    patch --batch --strip=1 --input="${PATCH}"
  fi
  
  # Install build dependencies
  sudo mk-build-deps --tool "apt-get -y --no-install-recommends" --install
  rm -f ${PROJECT}-build*.deb
}

build ( ) {
  # Fetch upstream archive
  # WARNING: the build fails if the version of the upstream tarball does not 
  # match the version of the package. Use --download-current-version
  uscan --force-download --download-current-version

  # Update changelog
  changelog_orig=$(mktemp)

  cp debian/changelog ${changelog_orig}

  version=$(dpkg-parsechangelog | awk '$1 ~ /Version:/ { print $2 }')
  dch \
    -v ${version}~${DISTRIB} --distribution ${DISTRIB} \
    --force-bad-version --force-distribution \
    "Backport to ${DISTRIB}"

  # Build all three independently to make sure "dh clean" is called each time
  DPKG_BUILDPACKAGE_OPTIONS="-j${JOBS} -us -uc"
  dpkg-buildpackage -S ${DPKG_BUILDPACKAGE_OPTIONS}
  grep "Architecture: all" debian/control && dpkg-buildpackage -A ${DPKG_BUILDPACKAGE_OPTIONS} || true
  grep "Architecture: any" debian/control && dpkg-buildpackage -B ${DPKG_BUILDPACKAGE_OPTIONS} || true
}

finish ( ) {
  # Run lintian, but do not record failures
  sudo ${APT_GET} --no-install-recommends install lintian
  lintian -I ../*changes || true
  
  mkdir -p ../source/packages
  cp ../*deb ../source/packages

  dh clean
  mv ${changelog_orig} debian/changelog

  if test -n "${PATCH}"; then
    patch --reverse --batch --strip=1 --input=${PATCH}
  fi
}

parse_args "$@"

prepare

build

finish
