#!/bin/bash

set -e
set -u

CONTACT=""
JOBS=1
PROJECT=""

while getopts "c:j:p:" OPT; do
  case ${OPT} in
    c) CONTACT=${OPTARG} ;;
    j) JOBS=${OPTARG} ;;
    p) PROJECT=${OPTARG} ;;
  esac
done

if test -z "${PROJECT}"; then
  echo "Missing project name"
  exit 1
fi

if test -z "${CONTACT}"; then
  echo "Missing contact"
  exit 1
fi

export DEBEMAIL="${CONTACT}"

APT_GET="apt-get -qq -y"
PATCHES=https://raw.githubusercontent.com/lamyj/packages/master/apt/patches
BINTRAY=http://dl.bintray.com/lamyj/generic

sudo rm -f /etc/apt/apt.conf.d/docker-clean
sudo -E ${APT_GET} update
sudo -E ${APT_GET} install gnupg wget lsb-release

DISTRIB=$(lsb_release -cs)

PACKAGES="devscripts dpkg-dev equivs"
# Needed for uscan on https
if [ "${DISTRIB}" = "precise" -o "${DISTRIB}" = "saucy" ]; then
  PACKAGES="${PACKAGES} libcrypt-ssleay-perl"
fi

wget -O - ${BINTRAY}/gpg.key | sudo apt-key add -
echo "deb ${BINTRAY}/apt ${DISTRIB} main" | sudo tee -a /etc/apt/sources.list
sudo -E ${APT_GET} update
sudo -E ${APT_GET} install ${PACKAGES}

# Patch if needed
patch_url=${PATCHES}/${PROJECT}/${DISTRIB}.patch
wget ${patch_url} && has_patch="yes" || has_patch=""
if test "${has_patch}"; then
  patch --batch --strip=1 --input=${DISTRIB}.patch
  rm ${DISTRIB}.patch
else
  echo "No patch for ${PROJECT} on ${DISTRIB}"
fi

# Install build dependencies
sudo mk-build-deps --tool "apt-get -y --no-install-recommends" --install
rm -f ${PROJECT}-build*.deb

# Fetch upstream archive
uscan --force-download

# Update changelog
changelog_orig=$(mktemp)

cp debian/changelog ${changelog_orig}

version=$(dpkg-parsechangelog | awk '$1 ~ /Version:/ { print $2 }')
dch \
  -v ${version}~${DISTRIB} --distribution ${DISTRIB} \
  --force-bad-version --force-distribution \
  "Backport to ${DISTRIB}"

dpkg-buildpackage -us -uc -j${JOBS}

# Run lintian, but do not record failures
sudo ${APT_GET} --no-install-recommends install lintian
lintian -I ../*changes || true

mkdir packages
cp ../*deb packages

./debian/rules clean
mv ${changelog_orig} debian/changelog
