version: '3'
services:
  build:
    image: ${IMAGE}
    volumes:
      - ${SOURCE}:/home/somebody/source
      - ./patches:/patches
      - ./backport:/backport
      - ./entry.sh:/entry.sh
      - ./incoming:/incoming
    entrypoint:
      - /entry.sh
      - /backport
    working_dir: /home/somebody

# e.g. IMAGE=debian:stretch SOURCE=~/src/odil/debian docker-compose -f ~/src/packages/apt/packaging.yml run --rm build -j4 -p /patches/odil/stretch.patch --backport "Julien Lamy <lamy@unistra.fr>" /home/somebody/source /incoming
# e.g. IMAGE=debian:sid SOURCE=~/src/odil/debian docker-compose -f ~/src/packages/apt/packaging.yml run --rm build -j4 -p /patches/odil/stretch.patch /home/somebody/source /incoming
