version: '3'
services:
  backport:
    image: ${IMAGE}
    volumes:
      - ${SOURCE}:/home/somebody/build
      - ./backport-docker:/backport-docker
      - ./entry.sh:/entry.sh
    entrypoint:
      - /entry.sh
      - /backport-docker
    working_dir: /home/somebody/build
  update-repo:
    build: 
      context: ./docker
      dockerfile: Dockerfile.sign
    volumes:
      - ./:/apt
    entrypoint:
      - /bin/bash
      - -i

# e.g. IMAGE=debian:stretch SOURCE=~/src/odil/debian docker-compose -f ~/src/packages/apt/packaging.yml run --rm backport -p odil -c "Julien Lamy <lamy@unistra.fr>" -j6
# e.g. docker-compose -f ~/src/packages/apt/packaging.yml run --name apt-update-repo update-repo
# docker start -i apt-update-repo
