#!/usr/bin/env python3

import argparse
import glob
import os
import re
import subprocess
import sys

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("key", help="GPG key id")
    arguments = parser.parse_args()

    local_root = os.path.abspath(os.path.dirname(__file__))

    # WARNING: may need to have key in gpg-agent before we sign
    run(local_root, arguments.key)

def run(local_root, key):
    unsigned_packages = []
    for filename in glob.glob(os.path.join(local_root, "incoming", "*deb")):
        if not is_signed(filename):
            unsigned_packages.append(filename)
    if unsigned_packages:
        subprocess.check_call(
            ["dpkg-sig", "--sign", "builder", "-k", key]+unsigned_packages)

    packages = {}
    for filename in glob.glob(os.path.join(local_root, "incoming", "*deb")):
        match = re.search(r"~(\w+)_\w+\.deb", filename)
        if match is None:
            print("WARNING: skipping {}".format(filename))
            continue
        dist = match.group(1)
        packages.setdefault(dist, []).append(filename)

    for dist, debs in packages.items():
        command = ["reprepro", "-b", ".", "includedeb", dist]+debs
        subprocess.call(command, cwd=local_root)

def is_signed(filename):
    result = None

    output = subprocess.run(
        ["dpkg-sig", "--list", filename], check=True, stdout=subprocess.PIPE).stdout
    output = [x.decode() for x in output.splitlines()]
    return ("builder" in output)

if __name__ == "__main__":
    sys.exit(main())
